export default {
    LOGIN_PENDING: 'auth/LOGIN_PENDING',
    LOGIN_ERROR: 'auth/LOGIN_ERROR',
    SET_TOKENS: 'auth/SET_TOKENS',
    SET_PASSWORD_TOKEN: 'auth/SET_PASSWORD_TOKEN',
    PASSWORD_PENDING: 'auth/PASSWORD_PENDING',
    PASSWORD_ERROR: 'auth/PASSWORD_ERROR',
    PASSWORD_SUCCESS: 'auth/PASSWORD_SUCCESS'
}