export default {
    PENDING: 'user/PENDING',
    ERROR: 'user/ERROR',
    SET_TOKENS: 'user/SET_TOKENS',
    GET_USER_SUCCESS: 'user/GET_USER_SUCCESS',
    GET_ALL_USERS_SUCCESS: 'user/GET_ALL_USERS_SUCCESS'
}