export default {
    CURRENT_USER_PENDING: 'user/CURRENT_USER_PENDING',
    CURRENT_USER_ERROR: 'user/CURRENT_USER_ERROR',
    CURRENT_USER_SUCCESS: 'user/CURRENT_USER_SUCCESS',
    ALL_USERS_PENDING: 'user/ALL_USERS_PENDING',
    ALL_USERS_ERROR: 'user/ALL_USERS_ERROR',
    ALL_USERS_SUCCESS: 'user/ALL_USERS_SUCCESS'
}