export default {
    MANAGERS_PENDING: 'team/MANAGERS_PENDING',
    MANAGERS_ERROR: 'team/MANAGERS_ERROR',
    MANAGERS_SUCCESS: 'team/MANAGERS_SUCCESS',
    USERS_PENDING: 'team/USERS_PENDING',
    USERS_ERROR: 'team/USERS_ERROR',
    USERS_SUCCESS: 'team/USERS_SUCCESS',
}